"""added specialties

Revision ID: 973cb3be3c88
Revises: 50f83ead6d36
Create Date: 2026-05-13 16:35:36.929243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973cb3be3c88'
down_revision: Union[str, Sequence[str], None] = '50f83ead6d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('hex_color', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_specialties_id'), 'project_specialties', ['id'], unique=False)
    op.add_column('project_members', sa.Column('specialty_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_members', 'project_specialties', ['specialty_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_column('project_members', 'specialty_id')
    op.drop_index(op.f('ix_project_specialties_id'), table_name='project_specialties')
    op.drop_table('project_specialties')
    # ### end Alembic commands ###
