"""columns added

Revision ID: 982e3caa6e74
Revises: fb5448d57ad9
Create Date: 2026-05-07 13:13:13.447638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982e3caa6e74'
down_revision: Union[str, Sequence[str], None] = 'fb5448d57ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'position', name='uq_project_column_position')
    )
    op.create_index(op.f('ix_board_columns_id'), 'board_columns', ['id'], unique=False)
    op.create_index(op.f('ix_board_columns_project_id'), 'board_columns', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_columns_project_id'), table_name='board_columns')
    op.drop_index(op.f('ix_board_columns_id'), table_name='board_columns')
    op.drop_table('board_columns')
    # ### end Alembic commands ###
